### ISSUE TITLE
Custom JSONParameters base on global JSON.Parameters

### ISSUE THREAD

**Issue by alesrazym** [mgholam/fastJSON#100]
I'd like to have option to (de)serialize some data with different `JSONParameters`, based on global `JSON.Parameters`.

`JSON.DeepCopy<JSONParameters>()` fails and `JSONParameters.MakeCopy()` is not public. Is there any other solution? Is it possible to make `JSONParameters.MakeCopy()` public?

**Comment by mgholam** [comment]
And how will making `JSONParameters.MakeCopy()` public help?

**Comment by alesrazym** [comment]
I don't want to change global `JSON.Parameters` itself, used widely in `JSON.ToJSON(object)`, but make a copy to change just a subset of parameters and use it in `JSON.ToJSON(object, JSON.Parameters)`.
For example I do not want to serialize type in global settings, but do want for some special case.

If I can make copy, then I can safely change one parameter withou knowing the others settings.

**Comment by mgholam** [comment]
You can easily do that right now :
```c#
var jp1 = new JSONParameters { UseExtensions = false }; // everything else as default
var jp2 = new JSONParameters { UseFastGuid = false };  
```

**Comment by alesrazym** [comment]
There is one global `JSON.Parameters` setup like that, changing few parameters.
I want to prevent any future change to global parameters to make a bug somewhere else by not inserting the change to other place in code where parameters are created. So whatever the `JSON.Parameters` are, I want to be sure to have a copy and change just one (or few) parameters.
Instead of:
```c#
JSON.Parameters = new JSONParameters
{
  something = true,
  ...,
  somethingElse = false
}
...
JSONParameters other = new JSONParameters
{
  something = true,
  ...,
  somethingElse = false,
  UseExtensions = true
}
```
I want to have:
```c#
JSON.Parameters = new JSONParameters
{
  something = true,
  ...,
  somethingElse = false
}
...
JSONParameters other = JSON.Parameters.MakeCopy();
other.UseExtensions = true;
```

**Comment by mgholam** [comment]
Made it public in `v2.2.3.1`

**Comment by alesrazym** [comment]
thank you sir
