### ISSUE TITLE
Readonly fields does not honour ShowReadOnlyProperties

### ISSUE THREAD

**Issue by xmedeko** [mgholam/fastJSON#104]
I have set `ShowReadOnlyProperties = false`, but the readonly fields are serialized. I have `public static readonly MyConstantClass MyConstant` filed and this field is serialized, too.

Please, do not serialize readonly field and do not serialize static fields/properties/methods.
Thanks

**Comment by mgholam** [comment]
`ShowReadOnlyProperties = false` ?

**Comment by xmedeko** [comment]
Yes, `ShowReadOnlyProperties = false`. I've checked the `Reflection.GetGetters` and the `ShowReadOnlyProperties` param is not used for fields.

**Comment by mgholam** [comment]
Thanks, will fix.

**Comment by mgholam** [comment]
Try `v2.2.5`

**Comment by xmedeko** [comment]
Works well, thanks for the quick fix.

**Comment by xmedeko** [comment]
@mgholam Serialization is OK. But deserialization still deserialize read-only fields if they are in JSON. I think the chage should be in Reflection.CreateSetField(..), probably something like:
```
if (fieldInfo.IsInitOnly)
    return null;
```

**Comment by mgholam** [comment]
Hmm... wouldn't you want to have it set if it is in the json string (and have the serializer controls this)?

**Comment by xmedeko** [comment]
Well, if you serialize/deserialize same class, then it's like you write.
But consider these scenarios:
1. JSON is from external resource, you want to read/deserialize selected properties only. And, by a coincidence, some JSON property has the same name as your read-only field. 
2. You do changes in your code, mark some filed read-only and do not want to serialize/deserialize it any more. But your new app version has to read the old save data, so your read-only filed is rewritten.

Also, check that `Reflection.CreateSetMethod(..)` returns null for read-only properties. IMO `Reflection.CreateSetField(..)` should behave consistently.

**Comment by mgholam** [comment]
Check the latest commit.

**Comment by xmedeko** [comment]
But no `ShowReadOnlyProperties` is involved in the condition. Probably should be:
```c#
if (ShowReadOnlyProperties || f.IsInitOnly == false)
    d.setter = Reflection.CreateSetField(type, f);
```

**Comment by mgholam** [comment]
For that, it will have to happen higher up the stack, since the setters are being cached (like the serializer).
