### ISSUE TITLE
ToObject error

### ISSUE THREAD

**Issue by MetSystem** [mgholam/fastJSON#105]
```
 string json = "{id:'1',name:'123'}";
            var type = Type.GetType("WebApi.Test", true, true);
            var data2 = fastJSON.JSON.ToObject(json, type);
```

```


namespace WebApi
{
    public class Test
    {
        public string id { get; set; }
        public string name { get; set; }
    }
}
```

**Comment by mgholam** [comment]
1) The json standard requires double quotes so add  `...3'}".Replace("'","\");` 
2) The json standard also requires double quotes around the property names, you can however overcome this by setting `fastJSON.JSON.Parameters.AllowNonQuotedKeys = true;` globally or on a call basis.
