### ISSUE TITLE
Unexpectedly reached end of string

### ISSUE THREAD

**Issue by frankinstien** [mgholam/fastJSON#113]
`{
ID:9a42a291cf824fb5935ab4462755321c,
UserName:logicalLogin,
Password:xyz156,
HashCode:1460319542,
AccessLevel:owner,
Database:CategoriesDb,
ConnectionId:NA,
Date:3/1/2020
}`

The above json causes an exception of "Unexpectedly reached end of string" and this is due to the first element ID value is being parsed as a number rather than a string or Guid. I've tried using the AllowNonQuotedKeys set to true but I still get the same exception. Is there another setting to deal with this scenario?

**Comment by frankinstien** [comment]
I believe the problem is that the json is anonymous. So fastJson doesn't parse anonymous json?

**Comment by mgholam** [comment]
Proper json is in `"property":"value"` format what you have shown is not json but javascript.
