### ISSUE TITLE
[Critical bug, Breaking change 2.3.3 -> 2.3.5]: StackOverflow Exception

### ISSUE THREAD

**Issue by AgentFire** [mgholam/fastJSON#118]
After updating from 2.3.3 to 2.3.5 I have stumbled upon this very unpleasant bug.
NuGet package version: 2.3.5 (latest, **stable**).

Minimal repro:

    class Program
    {
        // Self-reference is now a problem that needs hotfixing.
        public sealed class Model
        {
            public Model[] Children { get; set; }
        }

        static void Main()
        {
            JSON.ToObject<Model>("{}");
        }
    }

Even this simple JSON and model setup does not behave as it used to.
![image](https://user-images.githubusercontent.com/5173466/97554026-3f980800-19e7-11eb-85d6-e27f302211f5.png)

**Comment by mgholam** [comment]
Hmmm, thanks, I will look into it.

**Comment by mgholam** [comment]
Checkout `v2.3.5.2`

**Comment by AgentFire** [comment]
Yup, you fixed it.
I'd also recommend you to deprecate 2.3.5 version via [NuGet site](https://www.nuget.org/packages/fastJSON/2.3.5) ([direct management link](https://www.nuget.org/packages/fastJSON/2.3.5/Manage).
