### ISSUE TITLE
F# Record Type

### ISSUE THREAD

**Issue by jon49** [mgholam/fastJSON#12]
F#'s record type doesn't come through. E.g.,

```json
{"$types":{"Wrapper.Functions+Error, Wrapper, Version=0.0.0.0, Culture=neutral, PublicKe
yToken=null":"1"},"$type":"1"}
```

I created the following record:

```fs
type Error = {Message: string}
let result = fastJSON.ToJson {Message = "my string"}
```

I tried just passing an `exception` object, the results were better but for some reason it didn't pass the `Message` property. I'm just using a string for now.

```json
{"$types":{"System.FormatException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089":"1"
},"$type":"1","HelpLink":null,"Source":"mscorlib","HResult":-2146233033}
```

**Comment by mgholam** [comment]
I have no experience with f# but it could be because of how f# implements "functional anonymous types" on top of the CLR.

**Comment by mgholam** [comment]
Try setting `EnableAnonymousTypes = true` and `UseExtensions = false` in `JSONParameters`
