### ISSUE TITLE
KeyValuePair<string, object>> in net 3.5

### ISSUE THREAD

**Issue by selo-dev** [mgholam/fastJSON#120]
Hello,
I use fastJson in .Net 3.5 and am not allowed to switch to .net 4.0 (sql crl).
I would like to use the KeyValuePaar Collections and they are only supported in .net 4.0.
Why? Why such a restriction here?

private void WriteValue(object obj) {
…
#if NET4
            else if (_params.KVStyleStringDictionary == false &&
                obj is IEnumerable<KeyValuePair<string, object>>)

                WriteStringDictionary((IEnumerable<KeyValuePair<string, object>>)obj);
#endif
…
}

**Comment by mgholam** [comment]
Probably an oversight, you can remove the conditional flag.

**Comment by selo-dev** [comment]
Hello, yes it works. Would be nice if you made this change to your branch too.

Thanks and regards

**Comment by mgholam** [comment]
Will do, thanks!
