### ISSUE TITLE
do not support .net8

### ISSUE THREAD

**Issue by FlameskyDexive** [mgholam/fastJSON#142]
do not support .net8, will it fixed in the future?

**Comment by mgholam** [comment]
The DLL files should work, the project should also work if you upgrade the framework version.

**Comment by FlameskyDexive** [comment]
> The DLL files should work, the project should also work if you upgrade the framework version.

thanks for reply so fast, cause "FormatterServices" is obsolete in .net8, i can't figure out any new api to replace this, so it can't be used in .net8 program.    the error details "Severity	Code	Description	Project	File	Line	Suppression State
Error	SYSLIB0050	'FormatterServices' is obsolete: 'Formatter-based serialization is obsolete and should not be used.' (https://aka.ms/dotnet-warnings/SYSLIB0050)", i use the source code to compile.

**Comment by mgholam** [comment]
Thanks, I will look into it.

**Comment by FlameskyDexive** [comment]
![image](https://github.com/mgholam/fastJSON/assets/8274346/986ef310-0158-4a33-a69e-bcd7ebf064d7)
error line720 in JSON.cs

**Comment by mgholam** [comment]
Try : 
```c#
o = System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(type);
```

**Comment by FlameskyDexive** [comment]
> Try :
> 
> ```cs
> o = System.Runtime.CompilerServices.RuntimeHelpers.GetUninitializedObject(type);
> ```
wow, it builds successful now, thanks so much!!!
