### ISSUE TITLE
Strange Serialization result

### ISSUE THREAD

**Issue by frankinstien111** [mgholam/fastJSON#143]
I put a class into a List within another class. Below are images of the objects before they are serialized:

![ArrayItem1](https://github.com/mgholam/fastJSON/assets/107665927/f4db02d9-5226-4ab3-8a1d-2d81d2724091)
![ArrayItem2](https://github.com/mgholam/fastJSON/assets/107665927/7d5725e4-7b0f-40db-a15e-a5909ee5973c)
![ArrayItem3](https://github.com/mgholam/fastJSON/assets/107665927/10b28716-5aae-4e19-96ca-448b5e2fa2bf)
![ArrayItem4](https://github.com/mgholam/fastJSON/assets/107665927/b6b566f3-328f-4d7e-9b87-ea65c6c39ac3)

This is what it serializes into:

`{"$type":"6","DimensionMatrix":[{"$type":"7","Dimension":1,"Label":"High Arousal","Mid":2.5,"Status":true,"Maxium":5,"Minimum":0},{"$i":21},{"$i":21},{"$i":21}],"Title":"ArousalValence","Errors":[],"HowToCompare":"isWithinRange","OperatorType":"maxPoint","Status":true}`

For some reason, it appears to optimize the array by serializing the first item in the array and then grouping all the others as {"$i":21},{"$i":21},{"$i":21}.   When it deserializes all the class labels are "High Arousal" which is incorrect.  Below is the class object definition:

`  [Serializable]
  public class MaxMidMin
  {
      [DataMember]
      public int Dimension { set; get; }
      [DataMember]
      public String Label { set; get; }
      private double _max { set; get; }
      private double _min { set; get; }
      public double Mid { set; get; }
      [DataMember]
      private bool maxWasSet;
      [DataMember]
      private bool minWasSet;
      public bool Status { set; get; }
      GenericIndexKey rangeKey;

      public MaxMidMin()
      {
          Dimension = 1;            
      }

      public MaxMidMin(int dim)
      {
          if (dim > 0)
              Dimension = dim;
          else
              throw new Exception("A dimension cannot be less than 1");
      }

      public MaxMidMin(string label, int dim = 1)
          :this(dim)
      {
          Label = label;
      }     

      [DataMember]
      public double Maxium
      {
          set
          {
              _max = value;
              maxWasSet = true;
              InitializeMidPoint();
          }
          get
          {
              return _max;
          }
      }

      [DataMember]
      public double Minimum
      {
          set
          {
              _min = value;
              minWasSet = true;
              InitializeMidPoint();
          }
          get
          {
              return _min;
          }
      }    
}
`

**Comment by frankinstien111** [comment]
Could you point me to where the code that makes that decision to consolidate the array objects is located? I'm under a time constraint to find a solution for this.

Thx

**Comment by mgholam** [comment]
`$type` and `$i` means you have circular references. All your `$i` are 21 in your sample.
debug `private void WriteObject(object obj)`

**Comment by frankinstien111** [comment]
The problem was the nested classes would return zero if its object key was null where it would not generate the correct hashcode. Also, the approach of inserting an uninitialized class object into a dictionary the serializer would throw an exception where returning zero from the hash function prevented the error. In any case, code was implemented to do both, return zero when not initialized, and when the object key is null initialize an object key.
