### ISSUE TITLE
Something like JsonConverter (Json.Net)

### ISSUE THREAD

**Issue by jogibear9988** [mgholam/fastJSON#15]
We have a Json Structure that looks like this:

    {  //outer type is a derived instance of AbstractWebRequest with Property "Name"
        Name = "GetBlaBlaRequest",
        Taskrequest = {  //is a Instance of "GetBlaBlaRequest"

        }
    }

I can deserialize this Json.Net using a JsonRequestConverter! Is something like this also possible in your Fastjson implementation?

In Json.Net my Converter looks like this:

       public override object ReadJson(
            JsonReader reader,
            Type objectType,
            object existingValue,
            JsonSerializer serializer)
        {
            // Load JObject from stream
            JObject jObject = JObject.Load(reader);

            // Create target object based on JObject
            T target = Create(objectType, jObject);

            // Populate the object properties
            serializer.Populate(jObject.CreateReader(), target);

            return target;
        }

and my create code:

        protected override AbstractWebRequest Create(Type objectType, JObject jObject)
        {
            const string requestTypeField = "Name";

            if (!jObject.FieldExists(requestTypeField))
            {
                return null;
            }
            var requestName = jObject[requestTypeField].Value<string>();
            var request = _container.ResolveNamed<IRequest>(requestName);
            AbstractWebRequest result = null;

            if (request is IInitialRequest)
            {
                result = new InitialWebRequest
                {
                    TaskRequest = (IInitialRequest)request
                };
            }
            if (request is ISubscriptionRequest)
            {
                result = new SubscriptionWebRequest
                {
                    TaskRequest = (ISubscriptionRequest)request
                };
            }
           
            return result;
        }

**Comment by jogibear9988** [comment]
You see, I resolve the Type of the Object after the Name Property is read, and after that JSON.Net fills the created Object with data!

Problem is, I cannot modify the JSON I recieve, but I want to switch to your serializer, cause we have a Performance problem!

**Comment by mgholam** [comment]
Currently no.

If you can do without a CLR type try deserializing with `To Dynamic()`

**Comment by jogibear9988** [comment]
Wouldn't it be possible to add the dictonry you have in the json ParseObject function to the delegate?
And a function is needed to populate a already generated object with the string

**Comment by mgholam** [comment]
The delegate currently only works for 1 property of type string, not for an entire structure.

**Comment by jogibear9988** [comment]
thanks for the information
