### ISSUE TITLE
ToObject deserialization with dictionary containing list

### ISSUE THREAD

**Issue by yojimbo87** [mgholam/fastJSON#16]
Hi, with current master branch I'm unable to deserialize json string which contains list/array of some values into `Dictionary<string, object>` using `ToObject` method. For example this works:

```
var json = @"{""foo"":""some string value"",""bar"":123,""obj"":{""foo"":""some string value"",""bar"":123}}";
		    
var dict1 = JSON.ToObject<Dictionary<string, object>>(json);
```

but this:

```
var json = @"{""list"":[1,2,3],""foo"":""some string value"",""bar"":123,""obj"":{""foo"":""some string value"",""bar"":123}}";
		    
var dict1 = JSON.ToObject<Dictionary<string, object>>(json);
```

fails with System.InvalidCastException: Unable to cast object of type 'System.Object' to type 'System.Collections.IList'. `Parse` method still works for both scenarios.

**Comment by mgholam** [comment]
Fixed in 2.1.17
