### ISSUE TITLE
byte[] deserialization issue

### ISSUE THREAD

**Issue by enrico-padovani** [mgholam/fastJSON#20]
Hi, 

I'm reading a file and put the result into an array of byte[] from the server, I've built a proxy with fastJSON that deserialize it back, the json returned from the server look like this: 

```
{
    "Meta": {
        "ResponseType": "Single",
        "Success": true,
        "CurrentPage": 1,
        "TotalPages": 1,
        "TotalResults": 1,
        "Messages": []
    },
    "Results": [
        "dGVzdA=="
    ]
} 
```

It fails calling "private object ChangeType(object value, Type conversionType)" last line: 
return Convert.ChangeType(value, conversionType, CultureInfo.InvariantCulture); 

before that line I've added: 
```
// 2016-04-02 - Enrico Padovani - proper conversion of byte[] back from string 
if (conversionType == typeof(byte[]))
    return Convert.FromBase64String((string)value);
```
and now it works as expected. 

Enrico

**Comment by HKatura** [comment]
I had the save issue i belive and i made a pull request here fixing the problem

https://github.com/mgholam/fastJSON/pull/19

**Comment by enrico-padovani** [comment]
Your pull request is fixing the problem in case of DataTable, in my use case it's just a plain byte[][] and is not hitting the code that you did change.

This happening in simple type conversion from string in the deserialization phase, the method is in the same file but another one. If I find some time I'll make a pull request, but It's really a matter of adding 2 lines of code!

**Comment by enrico-padovani** [comment]
Ok, I did the pull request #22 with a test that failed before the changes.
