### ISSUE TITLE
I got some Problem in compile DLL with dynamic method

### ISSUE THREAD

**Issue by kmlxk** [mgholam/fastJSON#26]
fastJSON is a great basic library that I use for years in most of my programs.
In order to use dynamic I decide to upgrade from 1.0  to 2.1.5.
But when I compiled, the method `ToDynamic` is not exists in the DLL.
I found the compile condition `net4` seems to working in VS2015 and SharpDeveloper.
So I tried to remove the compile condition line in the following code:
```
#if net4
        /// <summary>
        /// Create a .net4 dynamic object from the json string
        /// </summary>
        /// <param name="json"></param>
        /// <returns></returns>
        public static dynamic ToDynamic(string json)
        {
            return new DynamicJson(json);
        }
#endif
```
Then I compiled in vs2015 and got the DLL with ToDynamic().
But SharpDevelop was unable to compile and raised Error CS0246: unabled to find “DynamicJson”.

I think there must be a better way to compile DLL with dynamic. 
Can anyone help me , thanks .

**Comment by mgholam** [comment]
Put a `net4` directive in the `Release` conditional compile option in the project file.
