### ISSUE TITLE
Using DataMember Attributes vs Propertie Names

### ISSUE THREAD

**Issue by zecompadre** [mgholam/fastJSON#27]
Sample Code of the issue:

=====================================

**Partial Sample public class Media**
.....
[DataMember(Name = "type_id")]
public EnumMediaType MediaType = EnumMediaType.UNDEFINED;

[DataMember(Name = "files")]
public List<MediaFile> MediaFiles = new List<MediaFile>();
.....

**Partial Sample class MediaFile**
.....
[DataMember(Name = "descriptionPT-PT")]
internal String DescriptionPTPT { get; set; }

[DataMember(Name = "descriptionEN-GB")]
internal String DescriptionENGB { get; set; }

[DataMember(Name = "descriptionES-ES")]
internal String DescriptionESES { get; set; }

[DataMember(Name = "descriptionES-CA")]
internal String DescriptionESCA { get; set; }

[DataMember(Name = "origin")]
internal String Source { get; set; }

[DataMember(Name = "video")]
internal String VideoURL { get; set; }

[DataMember(Name = "thumbnail")]
internal String VideoThumbnailURL { get; set; }

[DataMember(Name = "thumbnailextension")]
internal String VideoThumbnailExtension { get; set; }

internal String DescriptionToIncludeOnImagePath { get; set; }

[DataMember(Name = "id")]
public String ID { get; set; }

[DataMember(Name = "ext")]
public String Extension { get; set; }
.....

string mediaJSON = "[
  {
    "type_id": "1",
    "files": [
      {
        "descriptionPT-PT": "46516_Papel-de-Parede-Casa-Branca-Washington-DC-Estados-Unidos-da-America_1600x1",
        "descriptionEN-GB": "",
        "descriptionES-CA": "",
        "descriptionES-ES": "",
        "id": "f8f00500-0000-0500-0000-00000020e79f",
        "url": "/f8f00500-0000-0500-0000-00000020e79f.jpg",
        "ext": "jpg"
      }]
  }
]":

List<Media> media = fastJSON.JSON.ToObject<T><List<Media>>(mediaJSON);

=======================================

this code fail to convert ToObject

is expecting a "MediaFiles" propertie but in json gets a "files" 

the json string is a 3rd party string and i cant change my class properties

can u take a look ?

tks

**Comment by mgholam** [comment]
`DataMember` attributes and name changing is not supported by `fastJSON`

**Comment by xmedeko** [comment]
Update: DataMember name changing is supported from ver. 2.1.14.
