### ISSUE TITLE
GenericsClass<Dictionary<string, IList<T>>>

### ISSUE THREAD

**Issue by johnearnshaw** [mgholam/fastJSON#28]
Hey guys,

I've been stuck with this issue for a couple of days and found a work around to my problem...

Attempting to deserialize a generic class where T is a dictionary<string, List<SomeOtherClass>> was trying to map the List<SomeOtherClass> as List<string>

Changing lines 835 and 836 of JSON.cs (inside the CreateStringKeyDictionary method) to the code below fixed the issue but probably not the most elegant of fixes and probably not the most ideal place to put the change.

`else if (values.Value is IList)
{
        var t = t2.GetGenericArguments()[0];
        val = CreateGenericList((List<object>)values.Value, t2, t, globalTypes);
}`

The problem was that the collection is created from t2 but t1 is typeof(System.String), when it needed to be the generic arg of t2 (the IList)

**Comment by mgholam** [comment]
Thanks John!

Do you have sample code for this which I can put in a test?
