### ISSUE TITLE
fastJSON naming compliance

### ISSUE THREAD

**Issue by cwaldron** [mgholam/fastJSON#29]
This may seem trite but fastJSON does not conform to C# naming convention.  This lack of naming conformity has been used as a reason not to adopt fastJSON.  For me to use it I would have to fork my own version.  I really don't want to do that for something as trivial as naming convention and compliance.

**Comment by mgholam** [comment]
You will have to explain what you mean.

**Comment by mgholam** [comment]
You will have to explain what you mean.

**Comment by cwaldron** [comment]
You have classes and namespaces that do not conform to proper Camel and Pascal casing.  For example, "namespace fastJSON" should be "namespace FastJson".  Please read the C# naming convention specification.  This class library is losing out on adoption due to this fact alone.  Many shops will not adopt a class library that does not conform to .NET coding standards.

**Comment by Naphier** [comment]
Really a silly thing, but this was the first thing I noticed. Personal style is not welcome in coding style! ;) It's a great package and I'd hate to see someone pass it up for this (seemingly) minor thing.

**Comment by cwaldron** [comment]
@Naphier, 
   It is not a "silly thing" in large shops where conformance and governance are high priorities.  That is why I  am respectfully asking the author to consider conforming to .NET naming conventions.

**Comment by Naphier** [comment]
@cwaldron What I meant was it was a silly thing that I had to mention it, I guess ;) Just trying to soften the blow. It's a free, opensource project so sometimes I guess we take what we can get ;) Certainly wasn't calling the idea a silly thing. Coding convention is super important!

**Comment by mgholam** [comment]
I will take this into consideration for the next project, unfortunately changing it now will break peoples code which is a far more serious affair.

**Comment by deviousasti** [comment]
^ This. Never break the build.
