### ISSUE TITLE
ToObject<Dictionary<string, List<AC>>>(jsonstr) is't work

### ISSUE THREAD

**Issue by chunlizh** [mgholam/fastJSON#34]
i having a Class named "AC", then i have define 
`Dictionary<string, List<AC>> AdjustConfig;`

> 

`    public class AC
    {
        public AC() { }
        public decimal Lo { get; set; }
        public decimal Ratio { get; set; }
    }`

ToObject<Dictionary<string, List<AC>>>(jsonstr) is't work

**Comment by mgholam** [comment]
What is the `jsonstr` value?

**Comment by chunlizh** [comment]
private static void DictListTest()
        {
            fastJSON.JSON.Parameters.UseExtensions = false;
            Dictionary<string, List<AC>> dictList = new Dictionary<string, List<AC>>();
            dictList.Add("P", new List<AC>());
            dictList["P"].Add(new AC() { });
            string jsonstr = fastJSON.JSON.ToJSON(dictList);

            Console.WriteLine();
            Console.WriteLine(jsonstr);

            Dictionary<string, List<AC>> dictList2 = fastJSON.JSON.ToObject<Dictionary<string, List<AC>>>(jsonstr);

            foreach (var k in dictList2)
            {
                Console.Write(k.Key);
                foreach (var v in k.Value)
                    Console.WriteLine(":\tLo:{0}\tRatio:{1}", v.Lo, v.Ratio);
            }

        }

> if set fastJSON.JSON.Parameters.UseExtensions = false,is't work

**Comment by mgholam** [comment]
Fixed, will post soon, thanks!
