### ISSUE TITLE
fastJSON.JSON.Instance?

### ISSUE THREAD

**Issue by Naphier** [mgholam/fastJSON#35]
Your article:
https://www.codeproject.com/Articles/159450/fastJSON
Instructs to use fastJSON.JSON.Instance which doesn't exist (at least in the .NET35 version). 
I'm glad it doesn't exist because that's sort of an ugly way to access the library.
Just wanted to make sure you're aware of the discrepancy. If it *is* different among versions I hope you will adopt a uniform usage.
Great work on this. I hope to lend a hand when possible. It's a nice step up from Json.NET (which is great, but overkill and *amazingly* yours is faster!). 

Cheers!

**Comment by mgholam** [comment]
Thanks! 
The article was done in an append only fashion, so it tracks the changes made through time, looking back I should have edited it when breaking changes were made and fixed the code samples.

To help along I have added the howto.md file for quick samples (which is a work in progress).

I will put some time aside to fix the article to reflect the current build throughout.
