### ISSUE TITLE
Serialize dictionary key with int type problem?

### ISSUE THREAD

**Issue by icsharp** [mgholam/fastJSON#37]
Like as below:
```csharp
var dict = new Dictionary<int, string>
{
	[123] = "666",
	[456] = "999"
};

var json = JSON.ToJSON(dict);
```
the serialized json string is :
```json
[{"k":123,"v":"666"},{"k":456,"v":"999"}]
```
but what i want is :
```json
[{123:"666"},{456:"999"}]
```

So is it a bug for serializing dictionary with the key to int type ???

**Comment by mgholam** [comment]
Thanks, I will look into it.

**Comment by mgholam** [comment]
If you consult the specs at [http://json.org/ ] you will see that all keys are strings in an object structure.
