### ISSUE TITLE
Nuget installation dotnet core

### ISSUE THREAD

**Issue by LodeVlaeminck** [mgholam/fastJSON#40]
Hi,

when adding this poject to dotnetcore via nuget I get the error 

```
Errors in  
    Package fastJSON 2.1.23 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package fastJSON 2.1.23 supports:
      - net20 (.NETFramework,Version=v2.0)
      - net35 (.NETFramework,Version=v3.5)
      - net40 (.NETFramework,Version=v4.0)
    One or more packages are incompatible with .NETStandard,Version=v1.6
```
A snippit from my dependencies: 
```
  "dependencies": {
    "fastJSON": "2.1.23",
    "NETStandard.Library": "1.6.0"
  },
```

**Comment by mgholam** [comment]
I don't have a build for .net core at the moment (hence no nuget package either).

**Comment by LodeVlaeminck** [comment]
Are you planning on adding .NET core ?

**Comment by mgholam** [comment]
Yes, as soon as it is stable enough, and I can get it working in VS2015 (currently complains that it is not installed properly on my machine).

**Comment by ricebus** [comment]
Now that .NET Core is stable and .NET Standard 2 is out, any chance of you supporting it?

**Comment by mgholam** [comment]
Yes, absolutely, it's on the top of my todo list.
