### ISSUE TITLE
Is there a typo at Line 164 of JSON.cs in ToJSON(object obj, JSONParameters param) method?

### ISSUE THREAD

**Issue by qaqz111** [mgholam/fastJSON#41]
Hi, I got confused with this line of code against it's comment:
https://github.com/mgholam/fastJSON/blob/master/fastJSON/JSON.cs#L164

The comment on this line says:
`// FEATURE : **enable** extensions when you can deserialize anon types`

But the code next line **disabled** `param.UseExtensions` property:
`if (param.EnableAnonymousTypes) { param.UseExtensions = false; param.UsingGlobalTypes = false; }`

Is it my misunderstanding?

And, should this line be moved into `JSONParameters.FixValues()` method which was designed to do this and was called earlier in this `ToJSON(object obj, JSONParameters param)` method?

**Comment by mgholam** [comment]
As far as I remember, anonymous types don't have setters and have ugly compiler generated type names which make the resulting json ugly, and you probably want to just pass the simple json anyway otherwise you would create a proper class for it [to other languages like javascript].

Hence the line disables the extensions.

**Comment by qaqz111** [comment]
OK I understand now. The comment means something like "when you can deserialize anon types but UseExtensions is enabled", so the code next line is used to correct this option.

And, about the process of the global static `Parameters` property of JSON class, I think there should be a local copy for each non-static object instance that used it. Can you please take a look at [this comment in #39](https://github.com/mgholam/fastJSON/issues/39#issuecomment-290450225).
