### ISSUE TITLE
HowTo.md link broken

### ISSUE THREAD

**Issue by AdrianBathurst** [mgholam/fastJSON#43]
Can't view HowTo.md, gets a 404

**Comment by mgholam** [comment]
Seems ok on my end, try refreshing. (the file is in the repo and can be downloaded fine)

**Comment by AdrianBathurst** [comment]
It's the link that's broken...it's the link / file name casing. The file is Howto.md, the link is howto.md

I get...

![2017-04-03_091212](https://cloud.githubusercontent.com/assets/9006517/24600830/503f9aae-184e-11e7-9fb0-18a55eefc4ce.png)

**Comment by mgholam** [comment]
Fixeed thanks :)
