### ISSUE TITLE
Customizable indentation depth

### ISSUE THREAD

**Issue by Ruuttu** [mgholam/fastJSON#44]
I would like to generate JSONs with 4 spaces per tab, which is more common than the 3 that fastJSON uses.

**Comment by mgholam** [comment]
You can change the number of spaces to 4 in the `indent` value in `Formatter.cs`

**Comment by Ruuttu** [comment]
This should arguably be something I can pass via JSONParameters rather than hardcoded.

**Comment by mgholam** [comment]
I will put it on my todo list.

**Comment by mgholam** [comment]
Fixed in v2.1.26 with `JSONParameters.FormatterIndentSpaces`
