### ISSUE TITLE
Surrogate Serialization

### ISSUE THREAD

**Issue by EmpireWorld** [mgholam/fastJSON#48]
Does fastJSON supporting Surrogate Serialization?

If not, let us know.

Thanks.

**Comment by mgholam** [comment]
Please explain more what you mean.

**Comment by EmpireWorld** [comment]
Please take a look at: https://msdn.microsoft.com/en-us/library/system.runtime.serialization.surrogateselector(v=vs.110).aspx

**Comment by mgholam** [comment]
The whole purpose of `fastJSON` is that surrogates are not needed.

**Comment by EmpireWorld** [comment]
But sometimes, some classes don't need the some properties to be serialized. we need a surrogate for specifying which properties to be serialized.

**Comment by mgholam** [comment]
Use `XmlIgnore` attribute for those properties you don't want to serialize.

**Comment by EmpireWorld** [comment]
I don't have access to the class.

**Comment by EmpireWorld** [comment]
I can't modify class source code. because the class is related to the unity game engine, i just want to serialize it to json format.

**Comment by mgholam** [comment]
Try and see what happens.

**Comment by EmpireWorld** [comment]
What do i try? How do i apply XmlIgnore attribute to a closed source?

**Comment by mgholam** [comment]
Try your surrogates.

**Comment by EmpireWorld** [comment]
How? does fastjson supports surogate selector?
