### ISSUE TITLE
Property with List and no setter is not serialized

### ISSUE THREAD

**Issue by czechdude** [mgholam/fastJSON#51]
Hi, I think that this is a bug when i don't have a setter on property which is a ```List``` or any ```IEnumerable``` and the values do not serialize, example:

```csharp
public class ServiceDescription
{
    public ServiceDescription()
    {
        Projects = new List<ProjectDescription>();
    }

    public string ProjectRoot { get; set; }

    public List<ProjectDescription> Projects { get; } 
}
```

After ```JSON.ToJSON(serviceDescription)``` I become only ```{"projectRoot":null}```

**Comment by mgholam** [comment]
It's by design, to get no setter in the output use `JSONParameters.ShowReadOnlyProperties= true`
