### ISSUE TITLE
Deserialize Dictionary<string, object> with custom objects

### ISSUE THREAD

**Issue by Bmak** [mgholam/fastJSON#53]
Hello! I have a problem trying to deserialize Dictionary<string, object> where including objects also could be Dictionary<string, object> or custom object.
Method JSON.ToObject<Dictionary<string, object> doesn't deserialize correctly. It's casting any objects in a dictionary to System.Object without checking if it IDictionary. As result, if I use custom Object in dictionary JSON can't deserialize it.

Here is code example:

```
Dictionary<string,object> dict = new Dictionary<string, object>();
        
Dictionary<string, object> pos = new Dictionary<string, object>();
pos.Add("lat", 0.123123d);
pos.Add("lon", 0.323123d);

string name = "foo";
int level = 25;

SomeClass[] sc = new SomeClass[2];
sc[0] = new SomeClass(123,"map");
sc[1] = new SomeClass(567,"zone");

dict.Add("pos", pos);
dict.Add("name", name);
dict.Add("level", level);
dict.Add("sc", sc);

string json = JSON.ToJSON(dict);
Dictionary<string, object> d = JSON.ToObject<Dictionary<string, object>>(json);
//d["pos"] type will be System.Object instead of Dictionary.

```

**Comment by mgholam** [comment]
What is the `json` string?

**Comment by Bmak** [comment]
```
string json = JSON.ToJSON(dict);
//gets this:
{"pos":{"lat":0.123123,"lon":0.323123},"name":"foo","level":25,"sc":[{"pos":123,"map":"map"},{"pos":567,"map":"zone"}]}
```

**Comment by mgholam** [comment]
Well since the `json` does not have type information, then `fastJSON` is doing what you told it and giving you `object`s as values.
Try serializing with the type information i.e. enabling the extensions.

**Comment by Bmak** [comment]
Hmm... Looks like that didn't help me as well:
`{"pos":{"lat":0.123123,"lon":0.323123},"name":"foo","level":25,"sc":[{"$type":"SomeClass, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","pos":123,"map":"map"},{"$type":"SomeClass, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null","pos":567,"map":"zone"}]}`

Json does have type information, but not for the dictionary. How to solve it?

**Comment by Bmak** [comment]
Solved. My mistake, I didn't notice to check switch off silverlight.
