### ISSUE TITLE
About RegisterCustomType

### ISSUE THREAD

**Issue by ZJArcher** [mgholam/fastJSON#55]
Hi~
When I use RegisterCustomType for some specified class usually meaning I want Serialize or Deserialize the Object with specified function. But ,if the class is a dictionary-like(just like ,not implement from IDictionary interface) the function i registered will not be invoke

**Comment by mgholam** [comment]
Please post your code.

**Comment by ZJArcher** [comment]
internal Helper()
            {
  ##              fastJSON.JSON.RegisterCustomType(typeof(DyObject), new fastJSON.Serialize(this.GetJson), new fastJSON.Deserialize(this.FromJson));
                GC.KeepAlive(this);
            }

            internal string GetJson(object _dyobject)
            {
                return ((DyObject)_dyobject).ToString();
            }

            internal object FromJson(object _jsonStr)
            {
                if (_jsonStr is String)
                {
                    Dictionary<string, object> dic = UnSerilize<Dictionary<string, Object>>((String)_jsonStr);
                    return new DyObject(dic);
                }
                else if (_jsonStr is Dictionary<string, object>)
                {
                    return new DyObject((Dictionary<string, object>)_jsonStr);
                }
                else
                {
                    return new DyObject();
                }
            }

            internal object CnvFromDic(object dic)
            {
                Dictionary<string, object> dy = dic as Dictionary<string, object>;
                if (dy != null)
                {
                    return new DyObject(dy);
                }
                else
                {
                    return null;
                }
            }

With above code, I want implement some specified method for serilize and deserilize the instance of DyObject. But it will not be invoke untill I adjust your code bellow:

![image](https://user-images.githubusercontent.com/1956479/30415990-08176014-995d-11e7-8a8f-b552f199d32b.png)

Thank u very match. I am from china and not be good at English.

**Comment by mgholam** [comment]
What is `DyObject`?

If you want to use `dynamic` types that is supported already.

**Comment by ZJArcher** [comment]
It is a custom type for some special purpose.

But , do u think the  fastJSON.JSON.RegisterCustomType function is easy to make misunderstanding for it don't work expectantly?

**Comment by mgholam** [comment]
`fastJSON.JSON.RegisterCustomType()`  is intended for `value` types that are converted to a single string representation, not for entire object tree structures.

**Comment by ZJArcher** [comment]
Ok , Thank u any way.
