### ISSUE TITLE
Bugs In string parsing

### ISSUE THREAD

**Issue by muh00mad** [mgholam/fastJSON#57]
The JSON standard specify that a string could contains
  1. Unicode character
  2. Escape Sequence (Unicode, Predefined)

And prohibit the use of control characters and the character (\ and ") because they will cause conflict,

In the function `JsonParser.ParseString`
  1. it ignore any unknown escape sequence and it don't give error nor append them in the result.
  2. it allow adding invalid Unicode escape sequence and i mean `\uGGGG`.
  3. it allow control characters.

**Comment by mgholam** [comment]
Feel free to edit the source and post the fixes.
