### ISSUE TITLE
Feature Request: Unity3D support

### ISSUE THREAD

**Issue by friuns2** [mgholam/fastJSON#60]
basicly all need to do is modify add !UNITY_5_3_OR_NEWER to #if !SilverLight 
i checked it runs in editor

**Comment by mgholam** [comment]
Can you be more explicit?

**Comment by friuns2** [comment]
Unity3d is like silverlight have limited .net framework which don't have DataSet, also it using aot compilation

**Comment by friuns2** [comment]
and on their asset store somebody trying to sell old fastJSON versions so good idea to publish there free version.
https://www.assetstore.unity3d.com/en/#!/search/page=1/sortby=relevance/query=fastJSON
