### ISSUE TITLE
Fails to Deserialize Dictionary<string, Dictionary<string,string>>

### ISSUE THREAD

**Issue by qyte** [mgholam/fastJSON#67]
Hello i have the following jstring:
`{
   "Section1" : {
      "Key1" : "Value1",
      "Key2" : "Value2",
      "Key3" : "Value3",
      "Key4" : "Value4",
      "Key5" : "Value5"
   }
}`
That is generated from calling fastJSON.JSON.ToNiceJSON on a Dictionary<string, Dictionary<string,string>> object.

When i try and call fastJSON.JSON.ToObject<Dictionary<string, Dictionary<string,string>>(jsontext) it just fails every time.

I just for the moment went ahead and made a new object of type Dictionary<string, StringDictionary> that is parsed just fine but i would rather not use StringDictionary.

Any suggestions would be welcome. (I prefer not to use extensions though)

Edit: I am using the latest source from github and i have tried with Net4 directive and without.

**Comment by mgholam** [comment]
I will look into it, in the meantime you can use `ToDynamic()` which will give you a a `dynamic` object.

**Comment by mgholam** [comment]
fixed in `v2.1.31`
