### ISSUE TITLE
int64 to string error

### ISSUE THREAD

**Issue by andreasql** [mgholam/fastJSON#70]
dear all, first of all, thank you so much for the project.... I'm moving from NewtonSoft JSON library but I do have a problem converting a JSON received output into my personal code...
I'm using here FastJSON 1.2.28 version, but if fails with 1.2.27 as well
 
the problem consists in a value being
{"id":9990552,"name":"xxxxx",....
where 9990552 is declared in my code as integer (32bit) but FastSJON fails managing it, raisng the
"Unable to cast object of type 'System.Int64' to type 'System.String'."
exception...
I found the failing code in the
internal object ParseDictionary(Dictionary<string, object> d, Dictionary<string, object> globaltypes, Type type, object input)
in the
case myPropInfoType.String: oset = (string)v; break;
line code 

so I personally made a temporary work around as
//case myPropInfoType.String: oset = (string)v; break;
// andrea
case myPropInfoType.String: 
    oset = Convert.ToString(v);
    break;
// /andrea

but I'm missing the reason why the exception is thrown... and, the underliying object model declares the value as Visual Basic integer (meaning an Int32) and the 9990552 value naturally stays in the Int32 signed integer boundaries without overflowing...
NewtonSoft JSON library manages this without excpetions..  

I'm attaching the web received JSON and the VB implementation of the code using it, for your consideration and help.
TIA
Andrea

[FastJSON fails on Int64 conversion.zip](https://github.com/mgholam/fastJSON/files/1728452/FastJSON.fails.on.Int64.conversion.zip)

**Comment by mgholam** [comment]
Your `ratePlanId` is defined as string and is being given a number `9990552`.
You can correct this by changing your definition.

I will look into changing the code to handle this automatically, thanks.

**Comment by mgholam** [comment]
Sorry for the delay Andrea, fixed now in `v2.1.30`

**Comment by andreasql** [comment]
hi Mehdi,
thank you so much :)
have a nice sunday
Andrea
