### ISSUE TITLE
com.alibaba.fastjson.JSONException: illegal state : 1002

### ISSUE THREAD

**Issue by LiuDongCai** [mgholam/fastJSON#74]
我的json:
{
    "status": "0",
    "data": {
        "mobile": "0980-111-111",
        "msg": ""
    },
    "bind_status": "1",
    "update": "2018-04-10 16:45:08",
    "is_login_time_out": "0"
}

JSONReader reader = new JSONReader(new StringReader(json));
reader.startObject();
while (reader.hasNext()){
       ……
}
reader.endObject();
错误出现在while (reader.hasNext())，这是什么原因，我该如何解决？

**Comment by mgholam** [comment]
This is the c# version not the java one.

**Comment by LiuDongCai** [comment]
我要如何解决它？
