### ISSUE TITLE
com.alibaba.fastjson.JSONException: illegal state : 1002

### ISSUE THREAD

**Issue by LiuDongCai** [mgholam/fastJSON#75]
my json:
{
"status": "0",
"data": {
"mobile": "0980-111-111",
"msg": ""
},
"bind_status": "1",
"update": "2018-04-10 16:45:08",
"is_login_time_out": "0"
}

JSONReader reader = new JSONReader(new StringReader(json));
reader.startObject();
while (reader.hasNext()){
……
}
reader.endObject();

The error happened at ：while (reader.hasNext())
How can i solve it?

**Comment by mgholam** [comment]
This is not `com.alibaba.fastjson`, this is c# `fastJSON`

**Comment by LiuDongCai** [comment]
i can't understand
