### ISSUE TITLE
Be able to deserialize not strict JSON syntax

### ISSUE THREAD

**Issue by xelloss1012** [mgholam/fastJSON#76]
Hello!,

We're currently using JSON.Net, but since we want to increase performance, we are trying to switch to fastJSON. Our requeriment is to change it in a transparent way so it works in the same way as JSON.Net does but without changing contents that are already serialized and saved in files, databases, etc..

As far as we have seen, we can handle most of the behaviour and API differences easily and also the output is very similar to that of JSON.Net. However, we have found a possible stopper: JSON.Net allows a more "liberal" input syntax, allowing us to deserialize a string that is not strictly JSON valid format but a Javascript object. 

For example, it allows us to deserialize properties that are not wrapped in quotes, but fastJSON do not:

`{a: 1}`

If we want to make it work using fastJSON we need to use a stricter syntax:

`{"a": 1}`

Even though I think fastJSON is doing it properly and probably this shouldn't be an issue (since the string is not a really valid JSON), JSON.Net allows it (and probably others serializers too), and by this reason we currently have already saved in our databases and files some JSON content that may not be strict (coming from user input).

What we wanted to know is if you have any plan or workaround to make this kind of behaviour to work. If you don't, please feel free to just close this issue :)

Just in case you decide to implement it, I think it could be a parameter to make it configurable in order to  not affect to the performance for those who don't need it.

Thank you ver much!

**Comment by mgholam** [comment]
Hmmm... it's not valid JSON as you said, I don't how you get such "json" since it's not standard and will give errors the only way I can think of is if you copy from javascript code (posting will generate valid json).

I would fix your data (better in the long run, and you will not be "damned" by the next developers :) ), if you feel the need the source is available for you to change.

**Comment by xelloss1012** [comment]
Hello!, thank you for your fast response.

Well... we get this kind of bad JSON because in some cases we allow the user (kind of admin user) to freely input or edit the text directly in a manual way using JSON format... and as long as the serializer understands it, is treated as a "valid" JSON and so it is saved (in databases, files, etc.) .

The current serializer handles this behaviour without problems, and then have allowed us to have a number of this contents coming from different sources and so on without us being even aware of the problem. Of course is not an ideal use case nor a good practice to let the user to manually edit config. contents and I expect some day we can give better tools to the users, but by the moment we can't change it... :)

I will talk to the managers to decide among fix the current data as you suggest (plus training our users, clients and developers to use the appropriate syntax xD), adapt the fastJSON source code to our needs or just leave the current serializer.

Unfortunately I don't think we have time to change the source code, but in case we do I will send you the pull request just in case you consider adding it to the master as a feature.

Thank you!

**Comment by kolodi** [comment]
If you are using JavaScript on frontend, why you just don't parse user's input as JavaScript object and then serialize it to JSON before saving

**Comment by mgholam** [comment]
As a side note: 
- What version of `Newtonsoft.JSON` are you using? 
I have heard that it has gotten much faster since I looked at it last (which was a long time ago).
- What performance numbers were you getting?

**Comment by mgholam** [comment]
I've changed the code to allow this using `JSONParameters.AllowNonQuotedKeys`, tell me how it goes.

**Comment by xelloss1012** [comment]
@kolodi: it sounds like a great idea, but unfortunately the input data comes from a piece of software that is not under our direct control... in fact is not made with the purpose of inputting JSON and config files, instead it's supposed to be a tool to enter descriptions and images to give content to the website (kind of CMS) and so on. But the clients need to use it also as a tool for easy configuration of the website... 

By this reason we don't have control of what the user enters until it comes to our part (the website) when the data is already entered and saved in database...  of course we can add some validations now that we have detected the problem, but anyway the damage is already done, we have a number of data inputted and have to to deal with it (by now). Besides, we have some files that are edited manually by internal admin user (using ftp, file system, etc.) so is dificult to have all validates it without introducing a lot of changes what unfortunately is not the purpuse of our team right now.

**Comment by xelloss1012** [comment]
@mgholam: we are using 8.0.2 but I see they are at 11.0.2, maybe we could give it a try to see if we get some performance improvement, but your version seems promising so we wanted to try and see :)

By the way, I have tested your last change and it seems to work, but unfortunately is failing when the value of a property has and ":" (I don't know if it fails in other circustances too). For example, if we pass `AllowNonQuotedKeys = True` we get an error when trying to deserialize something like:

`
{a: "1:2"} `

Or:

`{"a": "1:2"}`

Thank you very much for your effort and help!, but I don't want to bother you more with this problem just so we can gain some ms :) (we still haven't compared the performance nor tried better ways to improve it). I'm just telling about this new error so you know ;)

Regards.

**Comment by mgholam** [comment]
The : in the string values is fixed (only happened with the `AllowNonQuotedKeys = true`).

**Comment by xelloss1012** [comment]
Oh!, now is working like a charm! 😄 

Thank you very much for your time and for your fast help!
