### ISSUE TITLE
FastJson references different assemblies

### ISSUE THREAD

**Issue by Alois-xx** [mgholam/fastJSON#77]
See issue https://github.com/Alois-xx/SerializerTests/issues/3
When compiling a cross platform application which targets .NET Core and .NET Framework I get
The type 'JSONParameters' exists in both 
'fastJSON, Version=2.1.0.0, Culture=neutral, PublicKeyToken=6b75a806b86095cd' and 
'fastJSON, Version=2.1.0.0, Culture=neutral, PublicKeyToken=nul

I have fixed this by copying from the net40 package the netstandard version. Can you update the Nuget package?

**Comment by mgholam** [comment]
I believe the problem may be that the assembly is not signed, I will look into it.

Thanks.

**Comment by mgholam** [comment]
Check the new post `v2.1.29`

**Comment by Alois-xx** [comment]
@mgholam: That works perfectly. Thanks for the fast response!
