### ISSUE TITLE
Make bool parse to accept integer values (0 and 1 (or other non-zero)).

### ISSUE THREAD

**Issue by AgentFire** [mgholam/fastJSON#80]
This data:

    {
        "is_verified": 0,
        "has_issues": 1
    }

Cannot be deserialized into an object with `bool` fields (`is_verified` and `has_issues` respectively), instead, it throws "Invalid cast" exception without any explanation.

I would like it to be less strict concerning such issues and convert zero to `false` and non-zero values to `true` if a target field has the `bool` type.

**Comment by mgholam** [comment]
fixed in `v2.1.33`
