### ISSUE TITLE
Performance comparing to Newton

### ISSUE THREAD

**Issue by detlefm** [mgholam/fastJSON#83]
Serialization (on my tests) are 10 to 20% faster but Deserialization is about 50% slower. What do I wrong?
Thats my numbers, the test program see Attachment

fastjson serialize
Min: 51,8532 Max: 121,6749 Average: 58,75316
newton serialize
Min: 61,8342 Max: 161,5994 Average: 67,778824
fastjson deserialize
Min: 185,503 Max: 278,2633 Average: 232,139316
newton deserialize
Min: 100,7489 Max: 137,6355 Average: 119,719818

The Max is normally the first run.

[FastJsonTest.zip](https://github.com/mgholam/fastJSON/files/2197240/FastJsonTest.zip)

**Comment by mgholam** [comment]
I haven't checked in a long time, let me see.

**Comment by mgholam** [comment]
I've tweaked `fastJSON` a bit but can't get the numbers down in this case.

I have rechecked my examples and here is the results on my machine :
```
.net version = 4.0.30319.42000
press key : (E)xotic
 -dataset

fastjson serialize      48      16      16      17      17
json.net4 serialize     219.1293        23.9834 22.999  24.5051 23.5052

fastjson deserialize    65      29      28      28      28
json.net4 deserialize   146.0598        31.9858 32.0041 31.0001 32.004

Exotic

fastjson serialize      72      39      40      39      39
json.net4 serialize     273.0187        71.014  71.9941 71.5002 71.9816

fastjson deserialize    124     86      83      85      84
json.net4 deserialize
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: Could not convert string 'consoletest.class1' to dictionary key type 'consoletest.baseclass'. Create a TypeConverter to convert from the string to the key type object. Path 'objectDictionary['consoletest.class1']', line 58, position 25. ---> Newtonsoft.Json.JsonSerializationException:
```
