### ISSUE TITLE
[NotFalse] [NotEmpty] attributes

### ISSUE THREAD

**Issue by arekbulski** [mgholam/fastJSON#88]
I would like the following code to fail during deserialization (throw an exception) so that I dont need to manually check these fields for their values. Can that be done using fastJSON?
```cs
class S 
{
  [NotNull] [NotFalse] truthy;
  [NotNull] [NotEmpty] text;
}

deserialize any of those, get an exception:
- {truthy: false}
- {text: null}
- {}
```

Would you be willing and able to merge a PR adding support for this into the core library? I am a maintainer on GitHub as well, Construct library for Python, so I can promise you clean code and test cases.

**Comment by mgholam** [comment]
Personally I would put these kind of data checks in the class in question via a method call, which would be used in the business logic, not really the job of the serializer.
