### ISSUE TITLE
Formatter.PrettyPrint not thread safe

### ISSUE THREAD

**Issue by xmedeko** [mgholam/fastJSON#96]
Formatter.PrettyPrint` manipulates the `private static string _indent` variable which is not thread safe.
Possible solutions:
- Change the class to non-static.
- Use C# 7 local function or delegate for `AppendIndent`.

Also, `Formatter.PrettyPrint(string input)` should use `JSON.Parameters.FormatterIndentSpaces` and not always three spaces.

Also, it would be handy to have `JSON.Beautify(string input, string indent)` for custom indent (e.g. a tab).

**Comment by mgholam** [comment]
Thanks! 
I will look into it.

**Comment by mgholam** [comment]
fixed in `v2.2.2`

**Comment by xmedeko** [comment]
Thanks for a quick fix. 👍 

You have left some commented out old code in the `Formatter.cs`.

I miss a bit `JSON.Beautify(string input, string indent)` but that's not so important. (Maybe the `JSON.Beautify` methods are obsolete?).

It's possible to close this issue.
